export const SERVERS = [
    // --- Ad Free / Premium (Top Priority) ---
    { name: 'VidLink (Ad Free 4K)', url: (id) => `https://vidlink.pro/movie/${id}`, isAdFree: true, type: 'Premium' },
    { name: 'AutoEmbed (Ad Free)', url: (id) => `https://autoembed.to/movie/tmdb/${id}`, isAdFree: true, type: 'Premium' },
    { name: 'VidSrc.to (Ad Free)', url: (id) => `https://vidsrc.to/embed/movie/${id}`, isAdFree: true, type: 'Premium' },

    // --- High Speed / Reliable ---
    { name: 'SuperEmbed (Fast)', url: (id) => `https://multiembed.mov/?video_id=${id}&tmdb=1`, isAdFree: false, type: 'Fast' },
    { name: '2Embed (Stabilized)', url: (id) => `https://www.2embed.cc/embed/${id}`, isAdFree: false, type: 'Fast' },
    { name: 'SmashyStream (FHD)', url: (id) => `https://player.smashy.stream/movie/${id}`, isAdFree: false, type: 'Fast' },
    { name: 'Vidsrc.pro (HLS)', url: (id) => `https://vidsrc.pro/embed/movie/${id}`, isAdFree: false, type: 'Fast' },
    { name: 'VidSrc.me (Legacy)', url: (id) => `https://vidsrc.me/embed/${id}`, isAdFree: false, type: 'Fast' },

    // --- Backups / Mirrors (Quantity) ---
    { name: 'VidCloud Operations', url: (id) => `https://vidcloud.co/embed/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'UpCloud Server', url: (id) => `https://upcloud.co/embed/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'DoodStream (Multi)', url: (id) => `https://dood.so/e/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'Voe (European)', url: (id) => `https://voe.sx/e/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'MixDrop (Global)', url: (id) => `https://mixdrop.co/e/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'StreamTape (Storage)', url: (id) => `https://streamtape.com/e/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'ClubServer (Vip)', url: (id) => `https://clubserver.net/e/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'Fembed (HD)', url: (id) => `https://fembed.com/v/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'Gomo (Asia)', url: (id) => `https://gomo.to/movie/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'Ridomovies', url: (id) => `https://ridomovies.tv/embed/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'WarezCDN', url: (id) => `https://warezcdn.com/embed/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'MCloud', url: (id) => `https://mcloud.to/embed/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'FileMoon', url: (id) => `https://filemoon.sx/e/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'StreamWish', url: (id) => `https://streamwish.com/e/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'VidHide', url: (id) => `https://vidhide.com/embed/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'Lulustream', url: (id) => `https://lulustream.com/e/${id}`, isAdFree: false, type: 'Backup' },
    { name: 'Vidoza', url: (id) => `https://vidoza.net/embed/${id}`, isAdFree: false, type: 'Backup' },

    // --- Fallbacks / Experimental ---
    { name: 'Server 26 (Auto)', url: (id) => `https://autoembed.to/movie/tmdb/${id}?server=2`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 27 (Auto)', url: (id) => `https://autoembed.to/movie/tmdb/${id}?server=3`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 28 (VidSrc Mirror)', url: (id) => `https://vidsrc.net/embed/movie/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 29 (Pro Mirror)', url: (id) => `https://vidsrc.xyz/embed/movie/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 30 (Vip Mirror)', url: (id) => `https://vidsrc.vip/embed/movie/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 31 (Super Mirror 1)', url: (id) => `https://multiembed.mov/?video_id=${id}&tmdb=1&s=1`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 32 (Super Mirror 2)', url: (id) => `https://multiembed.mov/?video_id=${id}&tmdb=1&s=2`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 33 (Super Mirror 3)', url: (id) => `https://multiembed.mov/?video_id=${id}&tmdb=1&s=3`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 34 (Super Mirror 4)', url: (id) => `https://multiembed.mov/?video_id=${id}&tmdb=1&s=4`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 35 (Super Mirror 5)', url: (id) => `https://multiembed.mov/?video_id=${id}&tmdb=1&s=5`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 36 (Soap2Day)', url: (id) => `https://soap2day.to/embed/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 37 (123Movies)', url: (id) => `https://123movies.net/embed/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 38 (Putlocker)', url: (id) => `https://putlocker.to/embed/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 39 (Solar)', url: (id) => `https://solarmovie.to/embed/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 40 (YesMovies)', url: (id) => `https://yesmovies.ag/embed/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 41 (FMovies)', url: (id) => `https://fmovies.to/embed/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 42 (GoStream)', url: (id) => `https://gostream.site/embed/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 43 (MoviesJoy)', url: (id) => `https://moviesjoy.to/embed/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 44 (LookMovie)', url: (id) => `https://lookmovie.io/embed/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 45 (Popcorn)', url: (id) => `https://popcorn.time/embed/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 46 (YTS)', url: (id) => `https://yts.mx/embed/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 47 (Rarbg)', url: (id) => `https://rarbg.to/embed/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 48 (Zoechip)', url: (id) => `https://zoechip.com/embed/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 49 (Afdah)', url: (id) => `https://afdah.info/embed/${id}`, isAdFree: false, type: 'Fallback' },
    { name: 'Server 50 (Cineb)', url: (id) => `https://cineb.net/embed/${id}`, isAdFree: false, type: 'Fallback' }
];
